["dedication", role="praise"]
== Elogios para 'Mastering Bitcoin'

[quote, Gavin Andresen, Científico Jefe de la Fundación Bitcoin]
____
“Cuando hablo sobre bitcoin a la audiencia en general, me preguntan a veces 'pero ¿como funciona realmente?' Ahora tengo una buena respuesta para esa pregunta, porque todo aquel que lea _Mastering Bitcoin_ contará con una profunda comprensión de cómo funciona y estará preparado para desarrollar la siguiente generación de sorprendentes aplicaciones de Criptomonedas.”
____

[quote, Naval Ravikant, Co-founder AngelList]
____
“Bitcoin and blockchain technologies are becoming fundamental building blocks for the next generation internet. Silicon Valley's best and brightest are working on it. Andreas' book will help you join the software revolution in the world of finance.” 
____

[quote, Balaji S. Srinivasan (@balajis), General Partner&#x2c; Andreessen Horowitz]
____
“_Mastering Bitcoin_ is the best technical reference available on bitcoin today. And bitcoin is likely to be seen in retrospect as the most important technology of this decade. As such, this book is an absolute must-have for any developer, especially those interested in building applications with the bitcoin protocol. Highly recommended.”
____

[quote, Roger Ver, Bitcoin Entrepreneur and Investor]
____
“The invention of the Bitcoin Blockchain represents an entirely new platform to build upon, one that will enable an ecosystem as wide and diverse as the Internet itself. As one of the preeminent thought leaders, Andreas Antonopoulos is the perfect choice to write this book.”
____